-- =============================================================================
-- Read-only user creation script for the `lcfs` database
-- Target: PostgreSQL 17
-- Generated by the `readonly-user-creation` skill.
--
-- Creates a single read-only LOGIN user (not a shared role) with SELECT access
-- to all existing and future tables, views, and sequences in the public schema.
--
-- Usage (variables keep credentials out of the file and are injection-safe):
--
--   psql -h <host> -U <admin_user> -d postgres \
--     -v username=lcfs_readonly \
--     -v password='CHANGE_ME_STRONG_PASSWORD' \
--     -v db_name=lcfs \
--     -v object_creator=postgres \
--     -f create-lcfs-readonly-user.sql
--
-- IMPORTANT:
--   * Run as a superuser or the `lcfs` database owner.
--   * Set `object_creator` to the role that CREATES tables (app/migration user).
--     ALTER DEFAULT PRIVILEGES only covers future objects made by that role.
--     Repeat the block in step 5 once per creating role if there are several.
--   * Repeat the schema-scoped statements for each schema if more than one.
--   * Never commit a real password.
-- =============================================================================

-- 1. Create the read-only login user
CREATE USER :"username" WITH PASSWORD :'password';

-- 2. Connect to the target database
\c :"db_name"

-- 3. Database + schema access
GRANT CONNECT ON DATABASE :"db_name" TO :"username";
GRANT USAGE ON SCHEMA public TO :"username";

-- 4. Read access to existing objects (tables + views + sequences)
GRANT SELECT ON ALL TABLES IN SCHEMA public TO :"username";
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO :"username";

-- 5. Read access to FUTURE objects created by the object creator role.
--    Repeat this block for each role that creates tables.
ALTER DEFAULT PRIVILEGES FOR ROLE :"object_creator" IN SCHEMA public
    GRANT SELECT ON TABLES TO :"username";
ALTER DEFAULT PRIVILEGES FOR ROLE :"object_creator" IN SCHEMA public
    GRANT SELECT ON SEQUENCES TO :"username";

-- =============================================================================
-- Verification (optional) — run after the script above.
-- =============================================================================

-- Existing table privileges for the user
-- SELECT table_schema, count(*)
-- FROM information_schema.role_table_grants
-- WHERE grantee = 'lcfs_readonly' AND privilege_type = 'SELECT'
-- GROUP BY table_schema;

-- Future-object default privileges
-- SELECT n.nspname AS schema, r.rolname AS creator, d.defaclacl
-- FROM pg_default_acl d
-- JOIN pg_namespace n ON n.oid = d.defaclnamespace
-- JOIN pg_roles r ON r.oid = d.defaclrole;
