apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: zeva2-cleanup
parameters:
  - name: LICENSE_PLATE
    description: license plate for the projec
    required: true
  - name: LOGIN_TOKEN_SECRET
    description: The secret having the login token
    required: true
objects:
  - kind: CronJob
    apiVersion: batch/v1
    metadata:
      name: zeva2-cleanup
    spec:
      schedule: 0 7 * * *
      concurrencyPolicy: Forbid
      suspend: false
      jobTemplate:
        metadata:
          creationTimestamp: null
        spec:
          backoffLimit: 0
          template:
            metadata:
              creationTimestamp: null
            spec:
              containers:
                - resources:
                    limits:
                      cpu: 100m
                      memory: 100Mi
                    requests:
                      cpu: 50m
                      memory: 50Mi
                  terminationMessagePath: /dev/termination-log
                  name: oc
                  command:
                    - /bin/sh
                    - "-c"
                  env:
                    - name: LOGIN_TOKEN
                      valueFrom:
                        secretKeyRef:
                          name: ${LOGIN_TOKEN_SECRET}
                          key: token
                  imagePullPolicy: Always
                  terminationMessagePolicy: File
                  image: >-
                    image-registry.openshift-image-registry.svc:5000/${LICENSE_PLATE}-tools/zeva2-cleanup:prod
                  args:
                    - >
                      date

                      oc login --token=$(LOGIN_TOKEN) --server=https://api.silver.devops.gov.bc.ca:6443

                      oc version

                      echo ""

                      echo "====> Cleaning up ${LICENSE_PLATE}-tools" 

                      echo "==========> Removing expired builds"

                      oc -n ${LICENSE_PLATE}-tools get builds | grep -E "Complete|Failed|Cancelled" | awk '{print $1}' | xargs oc -n ${LICENSE_PLATE}-tools delete build || true

                      echo "==========> Removing expired frontend and backend image tags"

                      oc -n ${LICENSE_PLATE}-tools get imagetags | grep -E "zeva2-next|zeva2-bullmq" | awk '{print $1}' | xargs oc -n ${LICENSE_PLATE}-tools delete imagetag || true

                      echo "==========> Removing expired pods"

                      oc -n ${LICENSE_PLATE}-tools get pods | grep -E "Completed|Error|ContainerStatusUnknown" | awk '{print $1}' | xargs oc -n ${LICENSE_PLATE}-tools delete pod || true

                      namespaces=("${LICENSE_PLATE}-dev" "${LICENSE_PLATE}-test")

                      for namespace in "${namespaces[@]}"; do

                          echo ""

                          echo "====> Cleaning up $namespace"

                          echo "==========> Removing expired pods"

                          oc -n $namespace get pods | grep Completed | awk '{print $1}' | xargs oc -n $namespace delete pod || true

                          oc -n $namespace get pods | grep -E "Error|ContainerStatusUnknown" | grep -v crunchy | awk '{print $1}' | xargs oc -n $namespace delete pod || true

                          env=$(echo $namespace | awk -F '-' '{print $NF}')

                          runningNextImageTag=$(oc -n $namespace describe deployment/zeva2-next-$env | grep Image | awk -F '/' '{print $3}' 

                          echo "==========> Removing expired backend image tags except  zeva2-next:$runningNextImageTag"
                          
                          oc -n $namespace get imagetags | grep zeva2-next | grep -v $runningNextImageTag | awk '{print $1}' | xargs oc -n $namespace delete imagetag || true

                          runningBullmqImageTag=$(oc -n $namespace describe deployment/zeva2-bullmq-$env | grep Image | awk -F '/' '{print $3}' 

                          echo "==========> Removing expired Bullmq image tags except zeva2-bullmq:$runningBullmqImageTag"

                          oc -n $namespace get imagetags | grep zeva2-bullmq | grep -v $runningBullmqImageTag | awk '{print $1}' | xargs oc -n $namespace delete imagetag || true

                      done

              restartPolicy: Never
              terminationGracePeriodSeconds: 30
              dnsPolicy: ClusterFirst
              securityContext: {}
              schedulerName: default-scheduler
      successfulJobsHistoryLimit: 3
      failedJobsHistoryLimit: 1
