export const testOrganizations = [
  {
    id: 1,
    name: "Alpha Org",
    supplierClass: "MEDIUM",
    zevUnitBalanceA: "2000",
    zevUnitBalanceB: "DEFICIT",
  },
  {
    id: 2,
    name: "Beta Org",
    supplierClass: "SMALL",
    zevUnitBalanceA: "100",
    zevUnitBalanceB: "3000",
  },
  {
    id: 3,
    name: "Gamma Org",
    supplierClass: "LARGE",
    zevUnitBalanceA: "5000",
    zevUnitBalanceB: "1000",
  },
  {
    id: 4,
    name: "Delta Org",
    supplierClass: "SMALL",
    zevUnitBalanceA: "1500",
    zevUnitBalanceB: "2000",
  },
  {
    id: 5,
    name: "Epsilon Org",
    supplierClass: "MEDIUM",
    zevUnitBalanceA: "2500",
    zevUnitBalanceB: "500",
  },
  {
    id: 6,
    name: "Zeta Org",
    supplierClass: "LARGE",
    zevUnitBalanceA: "8000",
    zevUnitBalanceB: "DEFICIT",
  },
  {
    id: 7,
    name: "Eta Org",
    supplierClass: "SMALL",
    zevUnitBalanceA: "300",
    zevUnitBalanceB: "700",
  },
  {
    id: 8,
    name: "Theta Org",
    supplierClass: "MEDIUM",
    zevUnitBalanceA: "4000",
    zevUnitBalanceB: "2500",
  },
];
