FROM artifacts.developer.gov.bc.ca/docker-remote/node:22.13.1

WORKDIR /next

COPY . .

RUN npm install

RUN npx prisma generate && npx prisma generate --schema prisma/schemaOld.prisma

CMD ["/bin/sh", "-c", ". /vault/secrets/config && npm run bullmq"]