FROM artifacts.developer.gov.bc.ca/docker-remote/node:22.13.1

WORKDIR /next

COPY . .

RUN npm install

RUN npx prisma generate && npx prisma generate --schema prisma/schemaOld.prisma

RUN npm run build

EXPOSE 3000

CMD [ "npm" , "run" , "start" ]