FROM artifacts.developer.gov.bc.ca/docker-remote/node:22.13.1

WORKDIR /next

COPY . .

RUN npm install

RUN npx prisma generate

CMD ["/bin/sh", "-c", "\
  for cfg in database minio redis email; do \
    if [ -f /vault/secrets/$cfg ]; then \
      . /vault/secrets/$cfg; \
    fi; \
  done; \
  npm run bullmq\
"]