FROM artifacts.developer.gov.bc.ca/docker-remote/node:24.14.1

WORKDIR /next

COPY . .

RUN npm install

RUN npm run generate-prisma-client

CMD ["/bin/sh", "-c", "\
  for cfg in database s3 redis email; do \
    if [ -f /vault/secrets/$cfg ]; then \
      . /vault/secrets/$cfg; \
    fi; \
  done; \
  npm run bullmq\
"]