FROM artifacts.developer.gov.bc.ca/docker-remote/node:22.13.1

RUN apt-get update && apt-get install -y bash

WORKDIR /next

ARG ZEVA2_VERSION
ENV ZEVA2_VERSION=$ZEVA2_VERSION

COPY . .

RUN npm install

RUN npm run generate-prisma-client && npm run generate-old-prisma-client

RUN npm run build

EXPOSE 3000

CMD ["/bin/sh", "-c", "\
  for cfg in database minio redis; do \
    if [ -f /vault/secrets/$cfg ]; then \
      . /vault/secrets/$cfg; \
    fi; \
  done; \
  npm run migrate && npm run start\
"]
