FROM artifacts.developer.gov.bc.ca/docker-remote/node:22.13.1

RUN apt-get update && apt-get install -y bash

WORKDIR /next

COPY . .

RUN npm install

RUN npx prisma generate && npx prisma generate --schema prisma/schemaOld.prisma

RUN npm run build

EXPOSE 3000

# CMD [ "npm" , "run" , "start" ]
CMD ["/bin/sh", "-c", ". /vault/secrets/config && npm run start"]

