# Manually promotes a specific version to the Test environment:
# - provide the image version to deploy
# - create a deployment pull request in the CD repository
# - after PR approval/merge, the version is deployed to OpenShift Test

name: Promote to Test (RC Release)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version to promote to Test:"
        required: true

permissions:
  contents: read
  issues: write

jobs:
  install-oc:
    uses: ./.github/workflows/install-oc-template.yaml

  deploy-test:
    name: Deploy Zeva2 to Test
    needs: install-oc
    uses: ./.github/workflows/deploy-template-by-pr.yaml
    with:
      git_ref: ${{ github.ref_name }}
      version: ${{ inputs.version }}
      tools_namespace: ${{ vars.OPENSHIFT_NAMESPACE_PLATE }}-tools
      values_file: values-test.yaml
      target_namespace: ${{ vars.OPENSHIFT_NAMESPACE_PLATE }}-test
      environment: test
    secrets:
      manifest-repo-deploy-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
      manifest-repo-token: ${{ secrets.MANIFEST_REPO_TOKEN }}
      openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}
